// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwbpRQRwPU97FJALBQfHxBYTr9exVUxJk',
    appId: '1:111902556312:web:e0121e42f97e1c2b4710ed',
    messagingSenderId: '111902556312',
    projectId: 'tasky-ee48e',
    authDomain: 'tasky-ee48e.firebaseapp.com',
    storageBucket: 'tasky-ee48e.firebasestorage.app',
    measurementId: 'G-13SX2XR3WQ',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7u2-l3HrcEvOjkPvM090VQXcjwuYDjy8',
    appId: '1:111902556312:ios:b8655e25cc4ba0784710ed',
    messagingSenderId: '111902556312',
    projectId: 'tasky-ee48e',
    storageBucket: 'tasky-ee48e.firebasestorage.app',
    iosBundleId: 'com.example.tasky',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7u2-l3HrcEvOjkPvM090VQXcjwuYDjy8',
    appId: '1:111902556312:ios:b8655e25cc4ba0784710ed',
    messagingSenderId: '111902556312',
    projectId: 'tasky-ee48e',
    storageBucket: 'tasky-ee48e.firebasestorage.app',
    iosBundleId: 'com.example.tasky',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwbpRQRwPU97FJALBQfHxBYTr9exVUxJk',
    appId: '1:111902556312:web:218a8676b8b0c5664710ed',
    messagingSenderId: '111902556312',
    projectId: 'tasky-ee48e',
    authDomain: 'tasky-ee48e.firebaseapp.com',
    storageBucket: 'tasky-ee48e.firebasestorage.app',
    measurementId: 'G-0WX7B6CN01',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpok4wa3LmwqU0yt8kluCpPMlE_tRs__s',
    appId: '1:111902556312:android:a9af4f3b0b2eba014710ed',
    messagingSenderId: '111902556312',
    projectId: 'tasky-ee48e',
    storageBucket: 'tasky-ee48e.firebasestorage.app',
  );

}